# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json
PackageIdentifier: Google.Chrome.Dev
PackageVersion: 116.0.5845.32
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2023-07-14
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise64.msi
  InstallerSha256: FFD954F848E302B72DB0B4747C605066DD95AF2B4C4276D15311317A6661C65F
  ProductCode: "{E92A2582-EEA4-3D18-B05C-8AE3E9B4AF3F}"
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise.msi
  InstallerSha256: 06CE11D429B9278798E91C00E909BE7129420ABFF96BD51734FD3AE6126C572D
  ProductCode: "{9AA7348E-BDFF-3CD5-84D0-274060F91C18}"
ManifestType: installer
ManifestVersion: 1.2.0

