# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json
PackageIdentifier: Google.Chrome.Beta
PackageVersion: 116.0.5845.62
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2023-08-07
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: D67FF8E10EC0FC16DAEB38174CBFFA007A1C4CF0F77A09267CC2F6D8781188DF
  ProductCode: "{7A873289-3469-3483-BA92-D646D9131823}"
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: 33DBEAC58ED1E8A1AF34A31ACBFCC625C9DE2E8F156A42D7AC6094953107525D
  ProductCode: "{5DB6D7AB-6CA8-3DFB-BC02-D9E4677C8337}"
ManifestType: installer
ManifestVersion: 1.2.0

