# Created with komac v2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Joplin.Joplin
PackageVersion: 3.1.22
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2024-11-04
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/laurent22/joplin/releases/download/v3.1.22/Joplin-Setup-3.1.22.exe
  InstallerSha256: 0F150AD051A39F25DEF943C5DB68216B62FF5482A39010A553E5E3823EB84F4C
  InstallerSwitches:
    Custom: /CURRENTUSER /RESTARTAPPLICATIONS
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/laurent22/joplin/releases/download/v3.1.22/Joplin-Setup-3.1.22.exe
  InstallerSha256: 0F150AD051A39F25DEF943C5DB68216B62FF5482A39010A553E5E3823EB84F4C
  InstallerSwitches:
    Custom: /ALLUSERS /RESTARTAPPLICATIONS
ManifestType: installer
ManifestVersion: 1.6.0
