# Created with komac v2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Joplin.Joplin
PackageVersion: 3.1.22
PackageLocale: en-US
Publisher: Laurent Cozic
PublisherUrl: https://github.com/laurent22/joplin
PublisherSupportUrl: https://github.com/laurent22/joplin/issues
PrivacyUrl: https://github.com/laurent22/joplin#privacy
Author: Laurent Cozic
PackageName: Joplin
PackageUrl: https://joplinapp.org/
License: AGPL-3.0-or-later
LicenseUrl: https://github.com/laurent22/joplin/blob/HEAD/LICENSE
Copyright: Copyright (c) 2016-2022 Laurent Cozic
CopyrightUrl: https://raw.githubusercontent.com/laurent22/joplin/dev/LICENSE
ShortDescription: Joplin is a free, open source note taking and to-do application, which can handle a large number of notes organised into notebooks.
Description: Joplin is a free, open source note taking and to-do application, which can handle a large number of notes organised into notebooks.
Tags:
- cross-platform
- foss
- joplin
- notes
- open-source
- todo
ReleaseNotes: |-
  - New: Custom CSS: Add cm-listItem class to lines with list items, don't add region start/end markers for items that are always single-line (#11291 by @personalizedrefrigerator)
  - Improved: Re-enable media with local file URLs in the note viewer (#11244 by @personalizedrefrigerator)
  - Improved: Remove left/right edge margin around editor content when disabled in settings (#11290) (#11279 by @personalizedrefrigerator)
  - Fixed: Fix content dropped into the Markdown editor is missing a cursor preview or dropped at the wrong location (#11289) (#11274 by @personalizedrefrigerator)
ReleaseNotesUrl: https://github.com/laurent22/joplin/releases/tag/v3.1.22
ManifestType: defaultLocale
ManifestVersion: 1.6.0
