# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Ablaze.Floorp.Daylight
PackageVersion: 11.17.7
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/beta/floorp-win64.installer.exe
  InstallerSha256: C1C6A0558DF772E31FABEDA696434B57C09E1B3E1121BC832DC9AB9F1EA63618
ManifestType: installer
ManifestVersion: 1.6.0
