# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json
PackageIdentifier: Google.Chrome.Beta
PackageVersion: 115.0.5790.98
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2023-07-18
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: BB195B43561F3877512851A12728047ECBCB872DCE6F9234C32A7F018F35328E
  ProductCode: "{13A003F4-5AE4-399A-9FD3-14209AF79237}"
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: 0C534E98109DED8E8EA9A472F75D55DAC9DC812AE8FE03EF935DD6BB05B2A6A6
  ProductCode: "{38FAF92B-4BF5-3866-897F-33FAAE22D10C}"
ManifestType: installer
ManifestVersion: 1.2.0

