# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: DuckStudio.FufuTools
PackageVersion: 1.3.2
PackageLocale: zh-CN
Publisher: DuckStudio
PublisherUrl: https://github.com/DuckDuckStudio
Author: DuckDuckStudio
PackageName: 芙芙工具箱
PackageUrl: https://github.com/DuckDuckStudio/Fufu_Tools
License: 芙芙工具箱许可文件
LicenseUrl: https://github.com/DuckDuckStudio/Fufu_Tools/blob/main/LICENSE
Copyright: Copyright © 鸭鸭「カモ」
ShortDescription: 芙芙工具箱是一个集合许多小工具的支持Windows的工具箱。
Moniker: Fufu_Tools
Tags:
- toolbox
- tools
- windows
ReleaseNotesUrl: https://github.com/DuckDuckStudio/Fufu_Tools/releases/tag/v1.3.2
ManifestType: defaultLocale
ManifestVersion: 1.6.0
