# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: TeamViewer.TeamViewer
PackageVersion: 15.59.5
Platform:
- Windows.Desktop
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Full\TeamViewer_Full.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI32.zip
  InstallerSha256: C445C387BCD94A50DE8F34C7DE06A31C127FF40376CA39FAC2E0B5ADFFA43398
  ProductCode: '{5947F819-D2AF-4147-AB33-4119D6DBE4C9}'
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://download.teamviewer.com/download/TeamViewer_Setup.exe
  InstallerSha256: A7F23352CF081165562621C09CB89A29461B8885377FF4F698E4A88F10E6CA55
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Full\TeamViewer_Full.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI64.zip
  InstallerSha256: 27214145EF51D9C7868FCD95CA4A4A86E607BEC238D742EA01004CCD55185894
  ProductCode: '{E489DC3B-12D0-4FC5-BD57-4A950BA336B3}'
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://download.teamviewer.com/download/TeamViewer_Setup_x64.exe
  InstallerSha256: F5BA0D0FAB79FAFF553D77B2BE94AD3B21D978AF62C716D580995978E2A316D6
ManifestType: installer
ManifestVersion: 1.6.0
