# Created with komac v2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Piriform.CCleaner
PackageVersion: '6.28'
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- ccleaner
FileExtensions:
- zzz
ReleaseDate: 2024-09-19
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\CCleaner'
  Files:
  - RelativeFilePath: uninst.exe
    FileSha256: 786FB3BE329F22C5EF886A28D05E679962F5045604B6093C4D2C763D3C653F02
    FileType: uninstall
Installers:
- InstallerLocale: en-GB
  Architecture: x86
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=2057
- InstallerLocale: en-GB
  Architecture: x64
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=2057
- InstallerLocale: en-US
  Architecture: x86
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=1033
- InstallerLocale: en-US
  Architecture: x64
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=1033
- InstallerLocale: ja-JP
  Architecture: x86
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=1041
- InstallerLocale: ja-JP
  Architecture: x64
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=1041
- InstallerLocale: ko-KR
  Architecture: x86
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=1042
- InstallerLocale: ko-KR
  Architecture: x64
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=1042
- InstallerLocale: ru-RU
  Architecture: x86
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=1049
- InstallerLocale: ru-RU
  Architecture: x64
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=1049
- InstallerLocale: zh-CN
  Architecture: x86
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=2052
- InstallerLocale: zh-CN
  Architecture: x64
  InstallerUrl: https://download.ccleaner.com/ccsetup628.exe
  InstallerSha256: 9C65EB247631A4140F59F8500FB0EBB05AFA0F1C9BC999905A0C960A43ABA313
  InstallerSwitches:
    Custom: /L=2052
ManifestType: installer
ManifestVersion: 1.6.0
