# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Amazon.Chime
PackageVersion: 5.23.32014.0
InstallerType: portable
UpgradeBehavior: uninstallPrevious
Commands:
- chime
ReleaseDate: 2025-01-23
Installers:
- Architecture: x86
  InstallerUrl: https://clients.chime.aws/win-nme/Chime-5.23.32014.exe
  InstallerSha256: 6EE6A2C8CB935F02D91E7D44F394F3B72114D325346DFCA5F0E6436B5E4B7D0D
ManifestType: installer
ManifestVersion: 1.9.0
