# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
#
PackageIdentifier: TeamViewer.TeamViewer.Host
PackageVersion: 15.59.5
Platform:
- Windows.Desktop
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Host\TeamViewer_Host.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI32.zip
  InstallerSha256: C445C387BCD94A50DE8F34C7DE06A31C127FF40376CA39FAC2E0B5ADFFA43398
  ProductCode: '{06861888-F286-46B6-A75B-0E82FFC83A2C}'
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://dl.teamviewer.com/download/version_15x/TeamViewer_Host_Setup.exe
  InstallerSha256: F0D9A7073EB9A2A4719636BD84F84A94AF2FC7F12B5A4631DCCC694EFC68AECF
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Host\TeamViewer_Host.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI64.zip
  InstallerSha256: 27214145EF51D9C7868FCD95CA4A4A86E607BEC238D742EA01004CCD55185894
  ProductCode: '{E561D4E9-AB2D-4ABA-8AC6-EDB107BF64CF}'
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://dl.teamviewer.com/download/version_15x/TeamViewer_Host_Setup_x64.exe
  InstallerSha256: AA001E931A12A1041A5C89A5BBF4A698FCAD8BF6513D4EB28C780561B391C812
ManifestType: installer
ManifestVersion: 1.6.0
