# Created using wingetcreate 1.6.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: TechSmith.Snagit.2024
PackageVersion: 24.2.0
InstallerType: burn
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- techsmithsnagit
FileExtensions:
- snag
- snagx
ProductCode: '{1a6d87a5-dbf8-4cb1-8531-04c536f19ef0}'
AppsAndFeaturesEntries:
- ProductCode: '{1a6d87a5-dbf8-4cb1-8531-04c536f19ef0}'
  UpgradeCode: '{6131DABB-A98B-4FCC-B0D5-DD42665E0289}'
Installers:
- Architecture: x64
  InstallerUrl: https://download.techsmith.com/snagit/releases/snagit.exe
  InstallerSha256: 1770DD57A550B4D71E07528EABD06E1241A4D1C0591DC54A6D5722564F1E6236
ManifestType: installer
ManifestVersion: 1.6.0
