# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json
PackageIdentifier: Google.Chrome.Beta
PackageVersion: 115.0.5790.90
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2023-07-13
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 19EE42905D69C42505CB50B4723EEBEAE6DD5D7661FF118926A321AD3BD167B6
  ProductCode: "{9180F956-D84E-39EE-B5E9-B14421026E67}"
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: 506C2AA2058EBE9D3AF9E8790B1E65E425F32C88211911FDD5CDB988FD481044
  ProductCode: "{7F0A2E65-36C2-3119-81E9-D044F4E0C517}"
ManifestType: installer
ManifestVersion: 1.2.0

